services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/myapp
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt:rw
    depends_on:
      - web
      - certbot
  certbot:
    image: certbot/certbot
    env_file:
      - .env
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do \
      certbot certonly --webroot -w /var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${HOST} || \
      certbot renew --webroot -w /var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${HOST}; \
      sleep 240h; done'
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot:/var/www/certbot
volumes:
  postgres_volume:
