services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    environment:
      - FRONTEND_ORIGIN=http://localhost:3000
    volumes:
      - .:/myapp
    # ports:
    #   - "3001:3001"
    expose:
      - "3001"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./certs-data/certbot/www:/var/www/certbot
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 240h & wait $${!}; done;'"
volumes:
  postgres_volume:
  certs:
  certs-data:
