services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    environment:
      - FRONTEND_ORIGIN=http://localhost:3000
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
volumes:
  postgres_volume:
